### ISSUE TITLE
GenericCatalog CreateDynamicExport returing null is some cases

### ISSUE THREAD

**Issue by jabbera** [MefContrib/MefContrib#1]
If the importDefinition passed to CreateDynamicExport is a non generic interface the return value could be null. This should never happen or the program will crash.

Using reflector on CatalogExportProvider::GetExportsCore you will see why:

foreach (Tuple<ComposablePartDefinition, ExportDefinition> tuple in valueAllowNull.GetExports(definition))

I see two solutions: set the export before the return value if it is null or change:

if (importDefinitionType.IsClass)
to
if (importDefinitionType.IsClass || importDefinitionType.IsInterface)

I don't know if that change is correct but for now it seems to work around my issue.

Mike

**Comment by thecodejunkie** [comment]
Sorry for the late reply! The author of this feature is currently on vacation .. I'll make sure he checks back as soon as he get back!

**Comment by chrise** [comment]
I hit across this as well. I had an ImportingConstructor with a string parameter.  I ended up checking importDefinitionType.IsSealed  to handle a typeof(string).

Also inside of GetExports I check to see if CreateDynamicExport(definition) returned a null, and if it did, to return the original exports enumeration.

Here is my code:

```
    private IEnumerable<Tuple<ComposablePartDefinition, ExportDefinition>> CreateDynamicExport(ImportDefinition definition)
    {
        var contractDef = (ContractBasedImportDefinition)definition;

        var importDefinitionType = TypeHelper.GetImportDefinitionType(definition);

        if (importDefinitionType.IsGenericType && TypeHelper.ShouldCreateClosedGenericPart(contractDef))
        {
            CreateGenericPart(importDefinitionType);
            var exports = _catalog.GetExports(definition);
            if (exports.Any()) return exports;
        }

        if (importDefinitionType.IsClass && !importDefinitionType.IsSealed)
        {
            CreateConcretePart(importDefinitionType);
            return _catalog.GetExports(definition);
        }

        return null;
    }

    public override IEnumerable<Tuple<ComposablePartDefinition, ExportDefinition>> GetExports(ImportDefinition definition)
    {
        var exports = _catalog.GetExports(definition);
        if (exports.Any()) return exports;

        if (TypeHelper.IsReflectionMemberImportDefinition(definition) || 
            TypeHelper.IsReflectionParameterImportDefinition(definition))
            exports = CreateDynamicExport(definition) ?? exports;

        return exports;
    }
```

**Comment by pwlodek** [comment]
Thank you for reporting the issue. Recently we have rewritten the GenericCatalog from the ground up, so that it uses InterceptingCatalog internally. The new version fixes the problem.
