### ISSUE TITLE
MefContrib.Integration.Unity: New Release no longer detects when objects are already instantiated in Unity

### ISSUE THREAD

**Issue by Jens-L** [MefContrib/MefContrib#12]
We are using CompositeIntegration to be able to instantiate an object with both Unity and MEF. The problem described below occurs now after upgrading to version 1.1. (Our code worked fine with previous versions of MefContrib)
## Expected Behavior: 

A class instantiates as MEF Export would not instantiated via MEF again, if it is already instantiated via Unity. (worked with prior version) 
e.g.,
 [Export(typeof(IEventAggregator))]
[PartCreationPolicy(CreationPolicy.Shared)]
public class EventAggregator : IEventAggregator
....
had been instantiated via Unity as a Singleton even though it was also declared as MEF Export as shown above.
## Observed Behavior in version 1.1: 

Classes now get instantiated via MEF even though they are already instantiated via Unity, e.g., the EventAggregator is no longer a singleton. 
## Further clues:

A diff of CompositeIntegration shows changes to this class, which seem to cause the issue. Esp. the new Initialize code seems to be modified above and beyond cosmetics. There are a new  Strategy and new Lazy policies declared, which indicate a potential place where the code now breaks: 
 Context.Policies.Set<IBuildPlanPolicy>(new LazyResolveBuildPlanPolicy(), typeof(Lazy<>));
 Context.Policies.SetDefault<ICompositionContainerPolicy>(  new CompositionContainerPolicy(compositionContainer));

Unfortunately, the sparse documentation of the code makes it very hard for us to debug the code, nor can we revert to the old version because of the memory leak. 

Therefore, quick help by the author of the change would be very much appreciated.

Thanks

Jens

**Comment by ChristopherN** [comment]
We have the same issue with version 1.1 here. We end up with two instances of a singleton, one is created by Unity and one by MEF. We used 0.9.2 before, where it worked correctly. 

Thanks for looking into this!
- Chris

**Comment by ChristopherN** [comment]
Ok, we were able to reproduce it. There's a Silverlight test project in the zip file:
http://dl.dropbox.com/u/7486199/MefContrib%20Tests.zip

MefContribTests.cs: Contains the unit test.
TestInfrastructure.cs: Contains classes that are resolved in the unit test.

Again: IEventAggregator is registered as singleton with unity (ContainerControlledLifetimeManager) and MEF (CreationPolicy.Shared), but we end up with two instances of that class. I would expect only one. With v0.9.2.0 it worked as expected.
If we remove the [Export] on EventAggregator, it works fine.

Regards,
Chris

**Comment by pwlodek** [comment]
Thank you for reporting this issue. It has now been fixed. Unity components always take the precedence over MEF components no matter Unity or MEF is queried.
