### ISSUE TITLE
MefContrib.Web.Mvc is not correctly handling per-request part creation

### ISSUE THREAD

**Issue by barryschulz** [MefContrib/MefContrib#13]
Example: 

A ShoppingCarController has dependencies on IOrdersRepository and IProductsRepository. Each repository has a dependency on IUnitOfWork. In order to correctly implement the unit of work pattern, both repositories need the same instance of IUnitOfWork. 

Currently, the CompositionDependencyResolver creates a filtered catalog based on the NonShared creation policy. 

This however causes the filtered container to create a new unit of work for every request during the web request. In my example, each repository will get a different unit of work, which is incorrect.

In order to work correctly, the creation policy must be shared for my IUnitOfWork implementation, but still exist in the filteredCatalog (current code seen below) in order to be disposed of at the end of the web request. 

I was able to solve this problem by creating another attribute to denote a per-request creation policy. My filteredCatalog now contains parts that are nonShared or that are annotated with the new attribute. 

Is this an appropriate solution?

  // Per-request container: only NonShared parts
            this.filteredCatalog = new FilteringCatalog(
                this.globalCatalog, new HasCreationPolicy(CreationPolicy.NonShared));

**Comment by maartenba** [comment]
That was actually the direction I was thinking in. I would even do this more granularly:
- Create a "Scope" attribute, which can be "PerRequest/PerApplication"
- Respect partcreationpolicy within that scope (so per-request can have both shared and nonshared)

This would be a breaking change though. Would it be appropriate to implement?

**Comment by maartenba** [comment]
Check https://github.com/maartenba/MefContrib

**Comment by barryschulz** [comment]
PartCreationScope.PerChildContainer and PartCreationScope.PerMasterContainer seem to reveal too much implementation detail. Using an enum similar to the [WebCreationPolicy](https://github.com/timjroberts/MefContrib/blob/master/src/MefContrib.Web/WebCreationPolicy.cs) possibly better indicates the intent of the annotation. 

Another possibility would be to take away the responsibility of part lifetime from the CompositionDependencyResolver and let the [derived](https://github.com/timjroberts/MefContrib/blob/master/src/MefContrib.Web/WebRequestScopedComposablePart.cs) composable part handle it.

**Comment by maartenba** [comment]
I can probably change that do be "PerRequest" / "PerApplication".
Feel free to refactor parts of my branch so we can get an adequate solution for the next version.

-----Original Message-----

**Comment by maartenba** [comment]
This one has been fixed. Wil soon appear in my fork.

**Comment by pwlodek** [comment]
The issue has now been fixed and included in MefContrib master branch.
