### ISSUE TITLE
MefContrib.Web.Mvc doubling up [ImportMany] parameters

### ISSUE THREAD

**Issue by AndyWorral** [MefContrib/MefContrib#18]
I recently upgraded my MefContribMVC3 using nuget and now have any parameters marked [ImportMany] on Controller constructors including the imported items twice.

I have a reference to the MEF Container created in the AppStart and if I request the same import using GetExports<> I only get the items once.

I am not sure what is causing the doubling up issue.

**Comment by AndyWorral** [comment]
I can fix the issue although I am not sure what I might have broken feature wise else where.

In MefContrib.Web.Mvc.CompositionDependencyResolver

Line 52, I commented out the globalContainer since it seemed to be adding the globalCatalog that was already added with filteredCatalog.

```
CurrentRequestContext.Items.Add(HttpContextKey, new CompositionContainer(this.filteredCatalog, true, null));
// this.globalContainer));
```

**Comment by maartenba** [comment]
Good one. Fixing it, will soon appear in my repo.

**Comment by pwlodek** [comment]
The issue has now been fixed and included in MefContrib master branch.
