### ISSUE TITLE
[ImportingContsructor] doesn't work with an open generic. 

### ISSUE THREAD

**Issue by jabbera** [MefContrib/MefContrib#2]
To fix add the following to TypeHelper

public static bool IsReflectionParameterImportDefinition(ImportDefinition definition)
{
return definition.GetType().Name.Equals("ReflectionParameterImportDefinition");
}

and change the following in GenericCatalog.GetExports(ImportDefinition definition): if (!exports.Any() && TypeHelper.IsReflectionMemberImportDefinition(definition))

to: if (!exports.Any() && (TypeHelper.IsReflectionMemberImportDefinition(definition) || TypeHelper.IsReflectionParameterImportDefinition(definition)))

**Comment by thecodejunkie** [comment]
Sorry for the late reply! The author of this feature is currently on vacation .. I'll make sure he checks back as soon as he get back!

**Comment by pwlodek** [comment]
Thank you for reporting the issue. The problem has been fixed.
