### ISSUE TITLE
ConventionPartCreator incorrectly gets import parameter definition for generic parameters                     

### ISSUE THREAD

**Issue by barryschulz** [MefContrib/MefContrib#20]
ConventionPartCreator.GetImportParameterDefinition(importConvention, parameter) currently uses parameter.ParameterType.GetActualType() to determine the parameter's importDefinition. This does not work for generic parameters. 

Ex: if Foo's ctor requires an IRepository<Bar>, GetImportParameterDefinition will determine that the contract name is Bar instead of IRepository(Bar). 

All ConventionPartCreatorTests and ConventionsCatalogTests passed with the following change to GetImportParameterDefinition 

 //var actualType = parameter.ParameterType.GetActualType();
   var actualType = parameter.ParameterType;

Am I missing something?

**Comment by barryschulz** [comment]
That should have been...

```
public Foo(IRepository<Bar> barRepository)
```

**Comment by pwlodek** [comment]
Hi, thank you for pointing this out. I fixed the issue.
