### ISSUE TITLE
Composition container not fully threadsafe

### ISSUE THREAD

**Issue by andyclap** [MefContrib/MefContrib#22]
When initializing composition integration, the composition container returned by `CompositionIntegration.PrepareCompositionContainer` is not threadsafe.

Can we have some way of overriding this so that we can use the constructor with the threadsafe flag, as per
http://msdn.microsoft.com/en-us/library/ee388345.aspx
passing a composition container factory for example.

**Comment by pwlodek** [comment]
Thanks for reporting this. All Unity extension methods now support isThreadSafe parameter which defaults to false. However, this parameter is exclusively used by MEF, and _not_ by plumbing infrastructure. If you think we need to synchronize somewhere before, tweet me at @pwlodek =)

**Comment by andyclap** [comment]
I have an intermittently failing stress-test that demonstrates this issue. Is it OK to reopen this? Having an option to enable the threadsafe flag (which resolves the issue) in the main codebase would help us out going forward.

**Comment by pwlodek** [comment]
Can you please elaborate more on this ? The thread safe flag has already been added to Unity/MEF integration layer. Note that you can fork our repo, implement the change you need, issue the pull request, I will review that change and if it does not violate any tests I will include it in main.
