### ISSUE TITLE
PartCreationScope does not work.

### ISSUE THREAD

**Issue by JelleHissink** [MefContrib/MefContrib#25]
I think the scope is case sensitive.
When I add 

<pre>[ExportMetadata("scope", "Global")]</pre> it works, if however I make it "Scope" it fails.
When I inspect the container after adding <pre>[PartCreationScope(PartCreationScope.Global)]</pre> it shows a scope with a upper-case letter.
MefContrib.Web.Mvc/Filter/HasPartCreationScope.cs line 52 thus should be 
<pre> var key = "Scope"</pre>

Regards,
Jelle

**Comment by maartenba** [comment]
Fixed in my fork.

**Comment by JelleHissink** [comment]
HI Maarten,

Thanks for the quick response!!!
Any plans to release a new nuget version any time soon? Or should I build upon your fork?

**Comment by maartenba** [comment]
It's on NuGet as of three seconds ago :-) Enjoy!

**Comment by JelleHissink** [comment]
Thanks!
