### ISSUE TITLE
Create CompositionInitializer and ExportFactory for Desktop version

### ISSUE THREAD

**Issue by kevmoo** [MefContrib/MefContrib#6]
See discussion here: http://reedcopsey.com/2010/03/26/mef-compositioninitializer-for-wpf/

Specifically, Glenn Block's post that he's re-created these for the Desktop. (Glenn's blog: http://blogs.msdn.com/b/gblock/)

Happy to work on the port. I think this could be useful.

**Comment by thecodejunkie** [comment]
Hi Kevin.. could you please head over to mefcontrib.com and click the feedback link on the left side of the screen and enter these? Thanks

**Comment by kevmoo** [comment]
http://mefcontrib.uservoice.com/forums/49409-general/suggestions/1158513-create-compositioninitializer-and-exportfactory-fo

Done.
