### ISSUE TITLE
ExportProvider.GetExportedValue<T>() does not work when using GenericExportHandler

### ISSUE THREAD

**Issue by fire-birdie** [MefContrib/MefContrib#7]
Calling `GetExportedValue<T>()` on a container making use of `GenericExportHandler` results in an `ArgumentException` thrown from `TypeHelper.GetImportDefinitionType(ImportDefinition)` (more specifically, the call to `ReflectionModelServices.IsImportingParameter(definition)` on line 14). The exception message is:

> ImportDefinition of type 'System.ComponentModel.Composition.Primitives.ContractBasedImportDefinition' cannot be used in this context. Only import definitions produced by the ReflectionModelServices.CreateImportDefinition are supported.
> Parameter name: importDefinition

**Comment by pwlodek** [comment]
Thank you for reporting the issue. The problem has been fixed.
